### ISSUE TITLE
remote signing

### ISSUE THREAD

**Issue by nicolasochem** [tqtezos/tezos-k8s#218]
- [x] ability to define remote signers in the topology and have bakers point to them - #220
- [x] ability to specify which addresses signers should sign for- #220
- [x] mask private keys from containers that need not know it- #220
- [ ] #232

**Comment by harryttd** [comment]
@nicolasochem Is this closable? Can you maybe add new tickets for supporting other signers? And making new milestones for them?
